# All options and their defaults.
#
# This is executed separately to the main configuration
# so that options are set before parsing the rest of the config.

# DO NOT USE -o IN YOUR OWN CONFIGURATION
set -ogq @ayu_appearance "dark"

set -ogq @ayu_status_background "default"

# Menu styling options
set -ogq @ayu_menu_selected_style "fg=#{@thm_fg},bold,bg=#{@thm_ui_line}"

# Pane styling options (DO NOT USE -o IN YOUR OWN CONFIGURATION)
set -ogq @ayu_pane_status_enabled "no" # set to "yes" to enable
set -ogq @ayu_pane_border_status "off" # set to "yes" to enable
# set -ogq @ayu_pane_border_style "fg=#{@thm_ui_line}"
set -ogq @ayu_pane_border_style "##{?pane_synchronized,fg=#{@thm_accent_on},fg=#{@thm_ui_line}}"
set -ogq @ayu_pane_active_border_style "##{?pane_in_mode,fg=#{@thm_ui_line},##{?pane_synchronized,fg=#{@thm_accent_tint},fg=#{@thm_accent_tint}}}"
set -ogq @ayu_pane_left_separator "█"
set -ogq @ayu_pane_middle_separator "█"
set -ogq @ayu_pane_right_separator "█"
set -ogq @ayu_pane_color "#{@thm_green}"
set -ogq @ayu_pane_background_color "#{@thm_ui_panel}"
set -ogq @ayu_pane_default_text "##{b:pane_current_path}"
set -ogq @ayu_pane_default_fill "number"
set -ogq @ayu_pane_number_position "left" # right, left

# NOTE: Changes to make the option names more intuitive and more closely follow
# the tmux naming conventions.
# @ayu_window_current_background -> @ayu_window_current_number_color
# @ayu_window_current_color      -> @ayu_window_current_text_color
# @ayu_window_default_background -> @ayu_window_number_color
# @ayu_window_default_color      -> @ayu_window_text_color
# @ayu_window_status             -> @ayu_window_flags
#
# Removed:
# @ayu_window_default_fill, @ayu_window_current_fill
# Just set the number and text colors.

# Window options (DO NOT USE -o IN YOUR OWN CONFIGURATION)
set -ogq @ayu_window_status_style "basic" # basic, rounded, slanted, custom, or none
set -ogq @ayu_window_text_color "#{@thm_ui_panel}"
set -ogq @ayu_window_number_color "#{@thm_ui_gutter}"
set -ogq @ayu_window_text " #T"
set -ogq @ayu_window_number "#I"
set -ogq @ayu_window_current_text_color "#{@thm_ui_selection}"
set -ogq @ayu_window_current_number_color "#{@thm_green}"
set -ogq @ayu_window_current_text " #T"
set -ogq @ayu_window_current_number "#I"
set -ogq @ayu_window_number_position "left"

# Window flags
set -ogq @ayu_window_flags "none"
set -ogq @ayu_window_flags_icon_last " 󰖰" # -
set -ogq @ayu_window_flags_icon_current " 󰖯" # *
set -ogq @ayu_window_flags_icon_zoom " 󰁌" # Z
set -ogq @ayu_window_flags_icon_mark " 󰃀" # M
set -ogq @ayu_window_flags_icon_silent " 󰂛" # ~
set -ogq @ayu_window_flags_icon_activity " 󱅫" # #
set -ogq @ayu_window_flags_icon_bell " 󰂞" # !
# Matches icon order when using `#F` (`#!~[*-]MZ`)
set -ogq @ayu_window_flags_icon_format "##{?window_activity_flag,#{E:@ayu_window_flags_icon_activity},}##{?window_bell_flag,#{E:@ayu_window_flags_icon_bell},}##{?window_silence_flag,#{E:@ayu_window_flags_icon_silent},}##{?window_active,#{E:@ayu_window_flags_icon_current},}##{?window_last_flag,#{E:@ayu_window_flags_icon_last},}##{?window_marked_flag,#{E:@ayu_window_flags_icon_mark},}##{?window_zoomed_flag,#{E:@ayu_window_flags_icon_zoom},} "

# Status line options (DO NOT USE -o IN YOUR OWN CONFIGURATION)
set -ogq @ayu_status_left_separator ""
set -ogq @ayu_status_middle_separator ""
set -ogq @ayu_status_right_separator " "
set -ogq @ayu_status_connect_separator "yes" # yes, no

# Maintain backwards compatibility. Use @ayu_status_module_bg_color if it is set.
set -ogq @ayu_status_module_text_bg "#{?@ayu_status_module_bg_color,#{E:@ayu_status_module_bg_color},#{@thm_ui_panel}}"
