# vim:set ft=tmux:

# --> ayu (Dark)
set -ogq @thm_bg "#0D1017"
set -ogq @thm_fg "#5A6378"

# Colors
set -ogq @thm_rosewater "#000000"
set -ogq @thm_flamingo "#000000"
set -ogq @thm_pink "#000000"
set -ogq @thm_accent_on "#765B24"
set -ogq @thm_red "#000000"
set -ogq @thm_maroon "#000000"
set -ogq @thm_peach "#000000"
set -ogq @thm_yellow "#000000"
set -ogq @thm_green "#ffffff"
set -ogq @thm_teal "#000000"
set -ogq @thm_sky "#000000"
set -ogq @thm_sapphire "#000000"
set -ogq @thm_blue "#FFFFFF"
set -ogq @thm_accent_tint "#E6B450"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#000000"
set -ogq @thm_subtext_0 "#000000"
set -ogq @thm_overlay_2 "#000000"
set -ogq @thm_overlay_1 "#000000"
set -ogq @thm_overlay_0 "#1B1F29" # ui.line
set -ogq @thm_surface_2 "#000000"
set -ogq @thm_surface_1 "#000000"
set -ogq @thm_surface_0 "#000000"
set -ogq @thm_mantle "#000000"
set -ogq @thm_crust "#000000"
