# vim:set ft=tmux:

# --> ayu (Dark)
set -ogq @thm_bg "#0D1017"
set -ogq @thm_fg "#5A6378"
set -ogq @thm_text "#BFBDB6"

# Colors
set -ogq @thm_rosewater "#FFFFFF"
set -ogq @thm_flamingo "#FFFFFF"
set -ogq @thm_violet "#D2A6FF"
set -ogq @thm_accent_on "#765B24"
set -ogq @thm_red "#F07178"
set -ogq @thm_magenta "#C385FE"
set -ogq @thm_peach "#FFFFFF"
set -ogq @thm_yellow "#FFFFFF"
set -ogq @thm_green "#AAD94C"
set -ogq @thm_teal "#95E6CB"
set -ogq @thm_sky "#172E51"
set -ogq @thm_sapphire "#FFFFFF"
set -ogq @thm_blue "#59C2FF"
set -ogq @thm_accent_tint "#E6B450"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#FFFFFF"
set -ogq @thm_subtext_0 "#FFFFFF"
set -ogq @thm_overlay_2 "#FFFFFF"
set -ogq @thm_overlay_1 "#FFFFFF"
set -ogq @thm_overlay_0 "#1B1F29" # ui.line
set -ogq @thm_surface_2 "#FFFFFF"
set -ogq @thm_surface_1 "#FFFFFF"
set -ogq @thm_surface_0 "#F26D78"
set -ogq @thm_mantle "#FFFFFF"
set -ogq @thm_crust "#FFFFFF"
