# vim:set ft=tmux:

# --> ayu (Dark)
set -gq @thm_bg "#10141C"
set -gq @thm_fg "#5A6378"
set -gq @thm_text "#BFBDB6"

# Colors
set -gq @thm_red "#F07178"
set -gq @thm_pink "#ED834B"
set -gq @thm_orange "#FF8F40"
set -gq @thm_peach "#D5B07C"
set -gq @thm_yellow "#F0A33A"
set -gq @thm_green "#AAD94C"
set -gq @thm_teal "#95E6CB"
set -gq @thm_indigo "#39BAE6"
set -gq @thm_blue "#59C2FF"
set -gq @thm_purple "#D2A6FF"
set -gq @thm_gray "#5A6673"
set -gq @thm_accent_on "#765B24"
set -gq @thm_accent_tint "#E6B450"

# Surfaces
set -gq @thm_editor_bg "#0B0E14"
set -gq @thm_ui_panel_bg "#0D1017"
set -gq @thm_ui_panel "#131721"
set -gq @thm_ui_line "#1B1F29"
set -gq @thm_ui_selection "#1C2433"
set -gq @thm_ui_gutter "#404953"
