# vim:set ft=tmux:

# --> ayu (Light)
set -gq @thm_bg "#FCFCFC"
set -gq @thm_fg "#8A9199"
set -gq @thm_text "#5C6166"

# Colors
set -gq @thm_red "#F07171"
set -gq @thm_pink "#EC6A53"
set -gq @thm_orange "#FA8532"
set -gq @thm_peach "#E59645"
set -gq @thm_yellow "#EBA400"
set -gq @thm_green "#86B300"
set -gq @thm_teal "#4CBF99"
set -gq @thm_indigo "#55B4D4"
set -gq @thm_blue "#22A4E6"
set -gq @thm_purple "#A37ACC"
set -gq @thm_gray "#939498"
set -gq @thm_accent_on "#F29718"
set -gq @thm_accent_tint "#FF9940"

# Surfaces
set -gq @thm_editor_bg "#FCFCFC"
set -gq @thm_ui_panel_bg "#F8F9FA"
set -gq @thm_ui_panel "#EFF0F1"
set -gq @thm_ui_line "#DCDEE0"
set -gq @thm_ui_selection "#D1E4F4"
set -gq @thm_ui_gutter "#ADAEB1"
