# vim:set ft=tmux:

# Embedded style that ensures that modules look "connected"
# when required.
set -gqF @_ayu_connect_style \
  "#{?#{==:#{@ayu_status_connect_separator},yes},,#[bg=default]}"

# There are four colors involved:
#
# - Icon
#   - fg: @ayu_status_[module]_icon_fg [default = editor_bg]
#   - bg: @ayu_status_[module]_icon_bg [required]
# - Text
#   - fg: @ayu_status_[module]_text_fg [default = foreground]
#   - bg: @ayu_status_[module]_text_bg [default = @ayu_status_module_text_bg]

set -ogqF "@ayu_status_${MODULE_NAME}_icon_fg" "#{E:@thm_editor_bg}"
set -ogqF "@ayu_status_${MODULE_NAME}_text_fg" "#{E:@thm_fg}"

%if "#{==:#{@ayu_status_${MODULE_NAME}_icon_bg},}"
  set -gqF "@ayu_status_${MODULE_NAME}_icon_bg" "#{@ayu_${MODULE_NAME}_color}"
%endif

%if "#{==:#{@ayu_status_${MODULE_NAME}_text_bg},}"
  set -gqF @_ayu_module_text_bg "#{E:@ayu_status_module_text_bg}"
%else
  set -gqF @_ayu_module_text_bg "#{@ayu_status_${MODULE_NAME}_text_bg}"
%endif

set -gF "@ayu_status_${MODULE_NAME}" \
  "#[fg=#{@ayu_status_${MODULE_NAME}_icon_bg}]#{@_ayu_connect_style}#{@ayu_status_left_separator}"

set -agF "@ayu_status_${MODULE_NAME}" \
  "#[fg=#{@ayu_status_${MODULE_NAME}_icon_fg},bg=#{@ayu_status_${MODULE_NAME}_icon_bg}]#{@ayu_${MODULE_NAME}_icon}"

set -agF "@ayu_status_${MODULE_NAME}" \
  "#{@ayu_status_middle_separator}"

set -agF "@ayu_status_${MODULE_NAME}" \
  "#[fg=#{@ayu_status_${MODULE_NAME}_text_fg},bg=#{@_ayu_module_text_bg}]"

set -ag "@ayu_status_${MODULE_NAME}" "#{E:@ayu_${MODULE_NAME}_text}"

set -agF "@ayu_status_${MODULE_NAME}" "#[fg=#{@_ayu_module_text_bg}]#{@_ayu_connect_style}#{@ayu_status_right_separator}"

set -ug @_ayu_connect_style
set -ug @_ayu_module_text_bg
